{"score": 70, "full_score": 100, "tests": {"docker_build_run": "PASS (10/10)", "run_docker_autograde": "PASS (0/0)", "protobuf_interface": "PASS (10/10)", "set_coefs": "PASS (10/10)", "predict": "PASS (10/10)", "predict_single_call_cache": "PASS (10/10)", "predict_full_cache_eviction": "PASS (10/10)", "set_coefs_cache_invalidation": "PASS (10/10)", "client_workload_1": "Traceback (most recent call last):\n  File \"/autograde/tester.py\", line 32, in run\n    result = self.func()\n             ^^^^^^^^^^^\n  File \"/autograde/docker_autograde.py\", line 42, in wrapper\n    check_output([\"python3\", \"client.py\", str(PORT), coefs_str, *csv_files])\n  File \"/usr/lib/python3.11/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['python3', 'client.py', '5440', '1,2,3', 'workload/workload1.csv']' returned non-zero exit status 1.\n", "client_workload_2": "Traceback (most recent call last):\n  File \"/autograde/tester.py\", line 32, in run\n    result = self.func()\n             ^^^^^^^^^^^\n  File \"/autograde/docker_autograde.py\", line 42, in wrapper\n    check_output([\"python3\", \"client.py\", str(PORT), coefs_str, *csv_files])\n  File \"/usr/lib/python3.11/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['python3', 'client.py', '5440', '1,2,3', 'workload/workload2.csv']' returned non-zero exit status 1.\n", "client_workload_3": "Traceback (most recent call last):\n  File \"/autograde/tester.py\", line 32, in run\n    result = self.func()\n             ^^^^^^^^^^^\n  File \"/autograde/docker_autograde.py\", line 42, in wrapper\n    check_output([\"python3\", \"client.py\", str(PORT), coefs_str, *csv_files])\n  File \"/usr/lib/python3.11/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['python3', 'client.py', '5440', '1,2,3', 'workload/workload1.csv', 'workload/workload2.csv']' returned non-zero exit status 1.\n"}}